### ISSUE TITLE
Data files need to be moved from a cloud storage service (Copy.com) that is shutting down.

### ISSUE THREAD

**Issue by welcheb** [gifforda/JMI_Gifford_WAT_CT_HU_vs_MRI_FSF#1]
Data files need to be moved from a cloud storage service (Copy.com) that is shutting down May 1, 2016. The best option is post the data as zip files associated with the github.com v1.0 release of this repository. Switching to zip files requires an updated download Python script and download CSV index file. Also, the MATLAB download files that do not work with zipped data files should be removed. Download instructions in the various README.md files should be updated.

**Comment by gifforda** [comment]
Solved by pull request #2
